//// <auto-generated />
//using LegalBotTest.Models;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace LegalBotTest.Migrations
//{
//    [DbContext(typeof(SurveyContext))]
//    partial class SurveyContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.4");

//            modelBuilder.Entity("LegalBotTest.Models.SurveyData", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("Accesibility")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("ImproveAccess")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("ImproveExperience")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("OverallExperience")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("ProvisionService")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Question")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Recommend")
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("SurveyData");
//                });

//            modelBuilder.Entity("LegalBotTest.Models.UserProfile", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("County")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Name")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Password")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("SubCounty")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("UserName")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Ward")
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("UserProfiles");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
